Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false