Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/MixinUsage:
  Enabled: false